### ISSUE TITLE
Are datasets open source？

### ISSUE THREAD

**Issue by JachyLikeCoding** [rsanchezgarc/micrograph_cleaner_em#5]
Hello, your work is very interesting! Are the training datasets open source?
Can you open the datasets? Thank you so much.

**Comment by rsanchezgarc** [comment]
Hi Jachy.

The dataset should be in one of my old lab's disk. I'll try to find it

**Comment by rsanchezgarc** [comment]
You should find it at http://campins.cnb.csic.es/micrograph_cleaner/
